# Generated by Django 4.2.4 on 2024-03-11 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserFavourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="DEFAULT", max_length=500)),
                ("address_line_1", models.CharField(default="DEFAULT", max_length=500)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("city", models.CharField(default="DEFAULT", max_length=500)),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("carlow", "Carlow"),
                            ("cavan", "Cavan"),
                            ("clare", "Clare"),
                            ("cork", "Cork"),
                            ("donegal", "Donegal"),
                            ("dublin", "Dublin"),
                            ("galway", "Galway"),
                            ("kerry", "Kerry"),
                            ("kildare", "Kildare"),
                            ("kilkenny", "Kilkenny"),
                            ("laois", "Laois"),
                            ("leitrim", "Leitrim"),
                            ("limerick", "Limerick"),
                            ("longford", "Longford"),
                            ("louth", "Louth"),
                            ("mayo", "Mayo"),
                            ("meath", "Meath"),
                            ("monaghan", "Monaghan"),
                            ("offaly", "Offaly"),
                            ("roscommon", "Roscommon"),
                            ("sligo", "Sligo"),
                            ("tipperary", "Tipperary"),
                            ("waterford", "Waterford"),
                            ("westmeath", "Westmeath"),
                            ("wexford", "Wexford"),
                            ("wicklow", "Wicklow"),
                        ],
                        default="DEFAULT",
                        max_length=50,
                    ),
                ),
                ("eircode", models.CharField(default="DEFAULT", max_length=8)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="useraddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", "True")),
                fields=("user", "is_default"),
                name="unique_default_address",
            ),
        ),
    ]
