# Generated by Django 4.2.4 on 2024-02-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("address_line_1", models.CharField(max_length=500)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("city", models.CharField(max_length=500)),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("carlow", "Carlow"),
                            ("cavan", "Cavan"),
                            ("clare", "Clare"),
                            ("cork", "Cork"),
                            ("donegal", "Donegal"),
                            ("dublin", "Dublin"),
                            ("galway", "Galway"),
                            ("kerry", "Kerry"),
                            ("kildare", "Kildare"),
                            ("kilkenny", "Kilkenny"),
                            ("laois", "Laois"),
                            ("leitrim", "Leitrim"),
                            ("limerick", "Limerick"),
                            ("longford", "Longford"),
                            ("louth", "Louth"),
                            ("mayo", "Mayo"),
                            ("meath", "Meath"),
                            ("monaghan", "Monaghan"),
                            ("offaly", "Offaly"),
                            ("roscommon", "Roscommon"),
                            ("sligo", "Sligo"),
                            ("tipperary", "Tipperary"),
                            ("waterford", "Waterford"),
                            ("westmeath", "Westmeath"),
                            ("wexford", "Wexford"),
                            ("wicklow", "Wicklow"),
                        ],
                        max_length=50,
                    ),
                ),
                ("eircode", models.CharField(max_length=8)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserFavourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
