# Generated by Django 4.2.4 on 2023-09-13 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userfavourite"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("address_line_1", models.CharField(max_length=500)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("city", models.CharField(max_length=500)),
                ("county", models.CharField(max_length=50)),
                ("eircode", models.CharField(max_length=8)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
