# Generated by Django 4.2.4 on 2023-09-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_useraddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="county",
            field=models.CharField(
                choices=[
                    ("carlow", "Carlow"),
                    ("cavan", "Cavan"),
                    ("clare", "Clare"),
                    ("cork", "Cork"),
                    ("donegal", "Donegal"),
                    ("dublin", "Dublin"),
                    ("galway", "Galway"),
                    ("kerry", "Kerry"),
                    ("kildare", "Kildare"),
                    ("kilkenny", "Kilkenny"),
                    ("laois", "Laois"),
                    ("leitrim", "Leitrim"),
                    ("limerick", "Limerick"),
                    ("longford", "Longford"),
                    ("louth", "Louth"),
                    ("mayo", "Mayo"),
                    ("meath", "Meath"),
                    ("monaghan", "Monaghan"),
                    ("offaly", "Offaly"),
                    ("roscommon", "Roscommon"),
                    ("sligo", "Sligo"),
                    ("tipperary", "Tipperary"),
                    ("waterford", "Waterford"),
                    ("westmeath", "Westmeath"),
                    ("wexford", "Wexford"),
                    ("wicklow", "Wicklow"),
                ],
                max_length=50,
            ),
        ),
    ]
