# Generated by Django 4.2.4 on 2023-09-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_useraddress_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="useraddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", "True")),
                fields=("user", "is_default"),
                name="unique_default_address",
            ),
        ),
    ]
