# Generated by Django 4.2.4 on 2024-02-04 11:11

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Product Name")),
                (
                    "sku",
                    models.CharField(
                        help_text="SKU must be unique and exactly 6 numerical characters",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="SKU must be exactly 6 numerical characters",
                                regex="[0-9]{6}",
                            )
                        ],
                        verbose_name="SKU",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500, verbose_name="Product Description"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=2, default=False, max_digits=10),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Featured Product?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("5.5", "UK 5.5"),
                            ("6", "UK 6"),
                            ("6.5", "UK 6.5"),
                            ("7", "UK 7"),
                            ("7.5", "UK 7.5"),
                            ("8", "UK 8"),
                            ("8.5", "UK 8.5"),
                            ("9", "UK 9"),
                            ("9.5", "UK 9.5"),
                            ("10", "UK 10"),
                            ("10.5", "UK 10.5"),
                            ("11", "UK 11"),
                            ("12.5", "UK 12.5"),
                            ("13", "UK 13"),
                        ],
                        max_length=50,
                        verbose_name="Size",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Qty in stock"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.models.upload_to_product_img,
                        verbose_name="Image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="core.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productvariant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="DEFAULT", max_length=500)),
                ("address_line_1", models.CharField(default="DEFAULT", max_length=500)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("city", models.CharField(default="DEFAULT", max_length=500)),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("carlow", "Carlow"),
                            ("cavan", "Cavan"),
                            ("clare", "Clare"),
                            ("cork", "Cork"),
                            ("donegal", "Donegal"),
                            ("dublin", "Dublin"),
                            ("galway", "Galway"),
                            ("kerry", "Kerry"),
                            ("kildare", "Kildare"),
                            ("kilkenny", "Kilkenny"),
                            ("laois", "Laois"),
                            ("leitrim", "Leitrim"),
                            ("limerick", "Limerick"),
                            ("longford", "Longford"),
                            ("louth", "Louth"),
                            ("mayo", "Mayo"),
                            ("meath", "Meath"),
                            ("monaghan", "Monaghan"),
                            ("offaly", "Offaly"),
                            ("roscommon", "Roscommon"),
                            ("sligo", "Sligo"),
                            ("tipperary", "Tipperary"),
                            ("waterford", "Waterford"),
                            ("westmeath", "Westmeath"),
                            ("wexford", "Wexford"),
                            ("wicklow", "Wicklow"),
                        ],
                        default="DEFAULT",
                        max_length=50,
                    ),
                ),
                ("eircode", models.CharField(default="DEFAULT", max_length=8)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
