# Generated by Django 4.2.4 on 2023-09-05 20:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_product_is_featured_product_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=core.models.upload_to_product_img, verbose_name="Image"
            ),
        ),
    ]
