# Generated by Django 4.2.4 on 2023-09-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_productimage_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("5.5", "UK 5.5"),
                            ("6", "UK 6"),
                            ("6.5", "UK 6.5"),
                            ("7", "UK 7"),
                            ("7.5", "UK 7.5"),
                            ("8", "UK 8"),
                            ("8.5", "UK 8.5"),
                            ("9", "UK 9"),
                            ("9.5", "UK 9.5"),
                            ("10", "UK 10"),
                            ("10.5", "UK 10.5"),
                            ("11", "UK 11"),
                            ("12.5", "UK 12.5"),
                            ("13", "UK 13"),
                        ],
                        max_length=50,
                        verbose_name="Size",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Stock"
                    ),
                ),
                (
                    "product_variant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productvariant",
                    ),
                ),
            ],
        ),
    ]
