# Generated by Django 4.2.4 on 2023-09-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_productvariant_productinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Qty in stock"
            ),
        ),
        migrations.DeleteModel(
            name="ProductInventory",
        ),
    ]
