# Generated by Django 4.2.4 on 2024-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_order_orderaddress_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.UUIDField(blank=True),
        ),
    ]
