# Generated by Django 4.2.4 on 2024-01-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_order_order_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id"], name="core_produc_id_6d8534_idx"),
        ),
    ]
