# Generated by Django 4.2.4 on 2024-01-26 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_product_core_produc_id_6d8534_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="core_produc_id_6d8534_idx",
        ),
    ]
