# Generated by Django 4.2.4 on 2024-02-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_product_core_produc_id_6d8534_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaddress",
            name="order",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.order"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="order_address",
                to="core.orderaddress",
            ),
        ),
    ]
