# Generated by Django 4.2.4 on 2024-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="DEFAULT", max_length=500)),
                ("address_line_1", models.CharField(default="DEFAULT", max_length=500)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("city", models.CharField(default="DEFAULT", max_length=500)),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("carlow", "Carlow"),
                            ("cavan", "Cavan"),
                            ("clare", "Clare"),
                            ("cork", "Cork"),
                            ("donegal", "Donegal"),
                            ("dublin", "Dublin"),
                            ("galway", "Galway"),
                            ("kerry", "Kerry"),
                            ("kildare", "Kildare"),
                            ("kilkenny", "Kilkenny"),
                            ("laois", "Laois"),
                            ("leitrim", "Leitrim"),
                            ("limerick", "Limerick"),
                            ("longford", "Longford"),
                            ("louth", "Louth"),
                            ("mayo", "Mayo"),
                            ("meath", "Meath"),
                            ("monaghan", "Monaghan"),
                            ("offaly", "Offaly"),
                            ("roscommon", "Roscommon"),
                            ("sligo", "Sligo"),
                            ("tipperary", "Tipperary"),
                            ("waterford", "Waterford"),
                            ("westmeath", "Westmeath"),
                            ("wexford", "Wexford"),
                            ("wicklow", "Wicklow"),
                        ],
                        default="DEFAULT",
                        max_length=50,
                    ),
                ),
                ("eircode", models.CharField(default="DEFAULT", max_length=8)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
